packages:
  - 'apps/*'
  - 'packages/*'
  - 'site-plan'
  - 'e2e'
allowBuilds:
  '@clerk/shared': true
  '@google/genai': set this to true or false
  core-js: set this to true or false
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  workerd: true
